[env]
_.python.venv = { path = ".venv", create = true }

[tools]
uv = "latest"
packer = "latest"
consul = "1.18.0"
vault = "1.21.1"
python = "3.13"


[settings]
python.uv_venv_auto = true

[tasks.install]
description = "Install dependencies"
run = "uv pip install -r requirements.txt"
